import type { AviaryListing, NestDoc, FinchDoc, TreasuryLedgerEntry } from "./schemas.ts";

/**
 * Seed data — pre-launch sample content.
 *
 * Everything here is marked `source: "seed"` and surfaces in the UI with a
 * SEED badge. Nothing in this file represents live onchain activity, real
 * usage metrics, or real treasury balances. When MongoDB is not configured,
 * API routes serve these rows read-only so the product is fully explorable.
 */

const t = (daysAgo: number): string => {
  const date = new Date("2026-09-02T12:00:00Z");
  date.setUTCDate(date.getUTCDate() - daysAgo);
  return date.toISOString();
};

// ── Aviary ────────────────────────────────────────────────────────────────

export const seedAviaryListings: AviaryListing[] = [
  {
    slug: "ticker-relay",
    name: "Ticker Relay",
    category: "data",
    description: "Normalized real-time quotes for Robinhood Chain tokens and tokenized equities. One schema, one subscription, every venue.",
    creator: { name: "finch-labs" },
    stats: { calls30d: 412_380, uptime90d: 99.97 },
    pricing: { model: "per_call", credits: 1 },
    chains: ["robinhood"],
    toolNames: ["token_data", "portfolio_snapshot"],
    verified: true,
    version: "0.4.2",
    source: "seed",
    createdAt: t(74),
  },
  {
    slug: "filing-digest",
    name: "Filing Digest",
    category: "research",
    description: "Parses filings, disclosures and issuer news into structured events with confidence scores. Built for News finches.",
    creator: { name: "aviary.dev" },
    stats: { calls30d: 88_410, uptime90d: 99.82 },
    pricing: { model: "per_call", credits: 4 },
    chains: ["robinhood"],
    toolNames: [],
    verified: true,
    version: "0.9.0",
    source: "seed",
    createdAt: t(68),
  },
  {
    slug: "order-router",
    name: "Order Router",
    category: "trading",
    description: "Swap routing with slippage guards, venue scoring and mandatory pre-trade simulation via Flightpath.",
    creator: { name: "finch-labs" },
    stats: { calls30d: 51_022, uptime90d: 99.91 },
    pricing: { model: "per_call", credits: 6 },
    chains: ["robinhood"],
    toolNames: ["swap_exact_in", "erc20_approve"],
    verified: true,
    version: "0.3.1",
    source: "seed",
    createdAt: t(61),
  },
  {
    slug: "risk-warden",
    name: "Risk Warden",
    category: "agents",
    description: "A composable risk finch: position limits, drawdown checks and a veto output for execution nests.",
    creator: { name: "quorum-birds", address: "0x7C3eA88B6e27cF1c4F1a1a3c9d41B2E85f10c9A4" },
    stats: { calls30d: 37_664, uptime90d: 99.74 },
    pricing: { model: "per_call", credits: 3 },
    chains: ["robinhood"],
    toolNames: ["portfolio_snapshot"],
    verified: true,
    version: "1.1.0",
    source: "seed",
    createdAt: t(57),
  },
  {
    slug: "rwa-navigator",
    name: "RWA Navigator",
    category: "rwa",
    description: "Catalog of approved RWA assets with issuer restrictions, eligibility checks and interaction templates.",
    creator: { name: "finch-labs" },
    stats: { calls30d: 12_930, uptime90d: 99.88 },
    pricing: { model: "free" },
    chains: ["robinhood"],
    toolNames: ["rwa_registry", "rwa_interact"],
    verified: true,
    version: "0.2.0",
    source: "seed",
    createdAt: t(52),
  },
  {
    slug: "chain-notary",
    name: "Chain Notary",
    category: "infrastructure",
    description: "Execution receipts → signed attestations. Lets a nest prove what its finches actually did onchain.",
    creator: { name: "attest.systems" },
    stats: { calls30d: 29_871, uptime90d: 99.95 },
    pricing: { model: "per_call", credits: 2 },
    chains: ["robinhood"],
    toolNames: ["contract_read"],
    verified: false,
    version: "0.5.3",
    source: "seed",
    createdAt: t(49),
  },
  {
    slug: "memory-loom",
    name: "Memory Loom",
    category: "infrastructure",
    description: "Managed vector memory namespaces on MongoDB Atlas with retention policies and recall analytics.",
    creator: { name: "finch-labs" },
    stats: { calls30d: 141_207, uptime90d: 99.99 },
    pricing: { model: "subscription", credits: 120 },
    chains: ["robinhood"],
    toolNames: [],
    verified: true,
    version: "0.8.0",
    source: "seed",
    createdAt: t(47),
  },
  {
    slug: "basket-weaver",
    name: "Basket Weaver",
    category: "trading",
    description: "Rebalancing agent for token baskets: drift detection, tax-aware ordering, budget-bounded execution.",
    creator: { name: "sparrowworks" },
    stats: { calls30d: 8_204, uptime90d: 99.31 },
    pricing: { model: "per_call", credits: 8 },
    chains: ["robinhood"],
    toolNames: ["portfolio_snapshot", "swap_exact_in"],
    verified: false,
    version: "0.2.4",
    source: "seed",
    createdAt: t(41),
  },
  {
    slug: "docket-watch",
    name: "Docket Watch",
    category: "research",
    description: "Tracks governance dockets and Finch Improvement Proposals; emits structured change events.",
    creator: { name: "quorum-birds" },
    stats: { calls30d: 5_120, uptime90d: 99.62 },
    pricing: { model: "free" },
    chains: ["robinhood"],
    toolNames: [],
    verified: false,
    version: "0.1.9",
    source: "seed",
    createdAt: t(38),
  },
  {
    slug: "uptime-canary",
    name: "Uptime Canary",
    category: "infrastructure",
    description: "Health probes for Aviary services. The uptime numbers on these cards come from this canary.",
    creator: { name: "aviary.dev" },
    stats: { calls30d: 622_040, uptime90d: 99.99 },
    pricing: { model: "free" },
    chains: ["robinhood"],
    toolNames: [],
    verified: true,
    version: "1.0.2",
    source: "seed",
    createdAt: t(36),
  },
  {
    slug: "macro-finch",
    name: "Macro Finch",
    category: "agents",
    description: "Reads the macro calendar, ranks event risk for your holdings and briefs downstream finches before market open.",
    creator: { name: "northroost" },
    stats: { calls30d: 19_552, uptime90d: 99.45 },
    pricing: { model: "per_call", credits: 5 },
    chains: ["robinhood"],
    toolNames: [],
    verified: false,
    version: "0.6.0",
    source: "seed",
    createdAt: t(31),
  },
  {
    slug: "bridge-scout",
    name: "Bridge Scout",
    category: "data",
    description: "Liquidity and route depth across EVM bridges into Robinhood Chain, refreshed each block.",
    creator: { name: "sparrowworks" },
    stats: { calls30d: 44_309, uptime90d: 99.7 },
    pricing: { model: "per_call", credits: 2 },
    chains: ["robinhood", "evm"],
    toolNames: [],
    verified: false,
    version: "0.3.0",
    source: "seed",
    createdAt: t(27),
  },
  {
    slug: "yield-surveyor",
    name: "Yield Surveyor",
    category: "rwa",
    description: "Yield curves for approved RWA instruments — treasury bills, money markets — with issuer terms attached.",
    creator: { name: "northroost" },
    stats: { calls30d: 9_884, uptime90d: 99.58 },
    pricing: { model: "per_call", credits: 3 },
    chains: ["robinhood"],
    toolNames: ["rwa_registry"],
    verified: true,
    version: "0.4.0",
    source: "seed",
    createdAt: t(22),
  },
  {
    slug: "compliance-gate",
    name: "Compliance Gate",
    category: "infrastructure",
    description: "Policy service for permissioned assets: allowlist checks, jurisdiction flags, human-approval webhooks.",
    creator: { name: "attest.systems" },
    stats: { calls30d: 15_730, uptime90d: 99.93 },
    pricing: { model: "subscription", credits: 200 },
    chains: ["robinhood"],
    toolNames: [],
    verified: true,
    version: "0.7.1",
    source: "seed",
    createdAt: t(18),
  },
  {
    slug: "swarm-conductor",
    name: "Swarm Conductor",
    category: "agents",
    description: "Nest orchestration templates: fan-out research, quorum voting, staged execution with rollback points.",
    creator: { name: "finch-labs" },
    stats: { calls30d: 6_090, uptime90d: 99.4 },
    pricing: { model: "per_call", credits: 10 },
    chains: ["robinhood"],
    toolNames: [],
    verified: true,
    version: "0.1.0",
    source: "seed",
    createdAt: t(12),
  },
  {
    slug: "execution-sim",
    name: "Execution Sim",
    category: "tools",
    description: "Dry-run sandbox: replay any Flightpath intent against a fork and diff the resulting state before going live.",
    creator: { name: "aviary.dev" },
    stats: { calls30d: 71_419, uptime90d: 99.86 },
    pricing: { model: "per_call", credits: 2 },
    chains: ["robinhood"],
    toolNames: ["contract_read"],
    verified: true,
    version: "0.9.5",
    source: "seed",
    createdAt: t(9),
  },
];

// ── Preset nests — coordinated swarms of finches around one objective ─────

const nestNode = (handle: string, name: string, role: string, inputs: string[], outputs: string[], permissions: string[]) => ({
  handle,
  name,
  role,
  inputs,
  outputs,
  permissions,
});

export const seedNests: NestDoc[] = [
  {
    slug: "pons-intelligence",
    name: "Pons Intelligence Nest",
    description: "Monitor new Pons launches, analyze structure, liquidity and activity; alert on criteria match.",
    stages: [
      { id: "s1", name: "Scout", finches: [nestNode("pons-scout", "Pons Scout", "Watches new Pons launches; emits structured launch events.", ["schedule.tick"], ["pons.launches"], ["read:pons"])] },
      {
        id: "s2",
        name: "Analysis",
        finches: [
          nestNode("holder-analyst", "Holder Analyst", "Maps holder distribution and concentration.", ["pons.launches"], ["holder.map"], ["read:chain"]),
          nestNode("liquidity-analyst", "Liquidity Analyst", "Profiles liquidity depth and lock structure.", ["pons.launches"], ["liq.profile"], ["read:chain"]),
        ],
      },
      { id: "s3", name: "Market", finches: [nestNode("market-finch", "Market Finch", "Forms a market view from holder + liquidity signals.", ["holder.map", "liq.profile"], ["market.view"], ["read:prices"])] },
      { id: "s4", name: "Risk", finches: [nestNode("risk-finch", "Risk Finch", "Scores risk; can veto downstream alerts.", ["market.view"], ["risk.score"], ["veto:downstream"])] },
      { id: "s5", name: "Verdict", finches: [nestNode("validator", "Validator", "Checks criteria match against the objective.", ["risk.score"], ["verdict"], ["read:objective"])] },
      { id: "s6", name: "Alert", finches: [nestNode("alert-finch", "Alert Finch", "Delivers matched-launch alerts.", ["verdict"], ["alert"], ["notify:user"])] },
    ],
    edges: [
      { from: "pons-scout", to: "holder-analyst", channel: "pons.launches" },
      { from: "pons-scout", to: "liquidity-analyst", channel: "pons.launches" },
      { from: "holder-analyst", to: "market-finch", channel: "holder.map" },
      { from: "liquidity-analyst", to: "market-finch", channel: "liq.profile" },
      { from: "market-finch", to: "risk-finch", channel: "market.view" },
      { from: "risk-finch", to: "validator", channel: "risk.score" },
      { from: "validator", to: "alert-finch", channel: "verdict" },
    ],
    status: "draft",
    createdAt: t(30),
    updatedAt: t(3),
  },
  {
    slug: "rwa-research",
    name: "RWA Research Nest",
    description: "Research tokenized equities and RWA assets into a structured report.",
    stages: [
      { id: "s1", name: "Signals", finches: [nestNode("news-finch", "News Finch", "Collects issuer news and filings.", ["schedule.tick"], ["news.events"], ["read:web"])] },
      { id: "s2", name: "Research", finches: [nestNode("research-finch", "Research Finch", "Deep context on the asset and issuer.", ["news.events"], ["research.notes"], ["read:web"])] },
      { id: "s3", name: "Analysis", finches: [nestNode("asset-analyst", "Asset Analyst", "Structure, permissioning, eligibility.", ["research.notes"], ["asset.profile"], ["read:rwa-registry"])] },
      { id: "s4", name: "Risk", finches: [nestNode("risk-finch", "Risk Finch", "Risk framing on the profile.", ["asset.profile"], ["risk.notes"], ["veto:downstream"])] },
      { id: "s5", name: "Report", finches: [nestNode("report-finch", "Report Finch", "Assembles the structured report output.", ["risk.notes"], ["research.report"], ["publish:report"])] },
    ],
    edges: [
      { from: "news-finch", to: "research-finch", channel: "news.events" },
      { from: "research-finch", to: "asset-analyst", channel: "research.notes" },
      { from: "asset-analyst", to: "risk-finch", channel: "asset.profile" },
      { from: "risk-finch", to: "report-finch", channel: "risk.notes" },
    ],
    status: "draft",
    createdAt: t(24),
    updatedAt: t(4),
  },
  {
    slug: "development",
    name: "Development Nest",
    description: "Analyze a repository, review code and security, test, and prepare deployment.",
    stages: [
      { id: "s1", name: "Source", finches: [nestNode("repository-finch", "Repository Finch", "Maps the repo and change surface.", ["task.spec"], ["repo.map"], ["read:repo"])] },
      { id: "s2", name: "Code", finches: [nestNode("code-finch", "Code Finch", "Implements against the spec.", ["repo.map"], ["diff"], ["write:branch"])] },
      { id: "s3", name: "Review", finches: [nestNode("security-finch", "Security Finch", "Reviews the diff for vulnerabilities.", ["diff"], ["security.review"], ["veto:downstream"])] },
      { id: "s4", name: "Test", finches: [nestNode("testing-finch", "Testing Finch", "Runs and extends the test suite.", ["security.review"], ["test.report"], ["run:tests"])] },
      { id: "s5", name: "Ship", finches: [nestNode("deployment-finch", "Deployment Finch", "Prepares the release; humans approve.", ["test.report"], ["release.candidate"], ["require:approval"])] },
    ],
    edges: [
      { from: "repository-finch", to: "code-finch", channel: "repo.map" },
      { from: "code-finch", to: "security-finch", channel: "diff" },
      { from: "security-finch", to: "testing-finch", channel: "security.review" },
      { from: "testing-finch", to: "deployment-finch", channel: "test.report" },
    ],
    status: "draft",
    createdAt: t(18),
    updatedAt: t(5),
  },
  {
    slug: "market-monitor",
    name: "Market Monitor Nest",
    description: "Watch markets, news, wallets and patterns; alert on what matters.",
    stages: [
      {
        id: "s1",
        name: "Watch",
        finches: [
          nestNode("market-finch", "Market Finch", "Tracks asset prices and movement.", ["schedule.tick"], ["market.ticks"], ["read:prices"]),
          nestNode("news-finch", "News Finch", "Tracks headlines and filings.", ["schedule.tick"], ["news.events"], ["read:web"]),
          nestNode("wallet-watcher", "Wallet Watcher", "Tracks configured wallets and flows.", ["schedule.tick"], ["wallet.events"], ["read:chain"]),
        ],
      },
      { id: "s2", name: "Patterns", finches: [nestNode("pattern-finch", "Pattern Finch", "Correlates ticks, news and flows into signals.", ["market.ticks", "news.events", "wallet.events"], ["signals"], ["read:context"])] },
      { id: "s3", name: "Alert", finches: [nestNode("alert-finch", "Alert Finch", "Delivers signal alerts.", ["signals"], ["alert"], ["notify:user"])] },
    ],
    edges: [
      { from: "market-finch", to: "pattern-finch", channel: "market.ticks" },
      { from: "news-finch", to: "pattern-finch", channel: "news.events" },
      { from: "wallet-watcher", to: "pattern-finch", channel: "wallet.events" },
      { from: "pattern-finch", to: "alert-finch", channel: "signals" },
    ],
    status: "draft",
    createdAt: t(12),
    updatedAt: t(2),
  },
];

// ── Example nests ─────────────────────────────────────────────────────────

export const seedFinches: FinchDoc[] = [
  {
    handle: "market-watcher",
    manifest: {
      schema: "finch.manifest/0.1",
      identity: {
        name: "Market Watcher",
        handle: "market-watcher",
        description: "Observer finch: tracks a token list and reports notable balance and supply changes.",
        instructions: "Watch the configured tokens. Report changes factually with numbers. Never speculate on price.",
        glyph: "finch-01",
      },
      model: { provider: "hyperbolic", model: "meta-llama/Llama-3.3-70B-Instruct", temperature: 0.2 },
      memory: { kind: "ephemeral", maxItems: 64 },
      tools: { flightpath: ["balance_native", "balance_erc20", "token_data", "portfolio_snapshot"], services: [] },
      permissions: { allowWrites: false, rwaApprovedOnly: true },
      wallet: { mode: "observer", allowances: [], allowedContracts: [] },
      triggers: [{ kind: "cron", schedule: "*/15 * * * *" }],
      budget: { maxActionsPerDay: 96, maxComputeCreditsPerDay: 200, maxToolStepsPerRun: 6, killSwitch: { maxConsecutiveFailures: 5 } },
      deployment: { runtime: "self-hosted", status: "draft" },
    },
    status: "draft",
    createdAt: t(20),
    updatedAt: t(20),
  },
];

// ── Treasury demo ledger ──────────────────────────────────────────────────
// DEMO DATA. $FINCH has not launched; there are no live creator fees yet.
// This ledger exists so The Nest dashboard is fully designed before launch,
// and is replaced by indexed onchain data the moment the FeeVault deploys.

export const seedTreasuryLedger: TreasuryLedgerEntry[] = [
  // Weekly creator-fee accruals (in), oldest first.
  { at: t(77), direction: "in", category: "creator-fees", amount: "0.42", asset: "ETH", memo: "Pons creator tax — week 1", source: "seed" },
  { at: t(70), direction: "in", category: "creator-fees", amount: "0.58", asset: "ETH", memo: "Pons creator tax — week 2", source: "seed" },
  { at: t(63), direction: "in", category: "creator-fees", amount: "0.51", asset: "ETH", memo: "Pons creator tax — week 3", source: "seed" },
  { at: t(56), direction: "in", category: "creator-fees", amount: "0.77", asset: "ETH", memo: "Pons creator tax — week 4", source: "seed" },
  { at: t(49), direction: "in", category: "creator-fees", amount: "0.94", asset: "ETH", memo: "Pons creator tax — week 5", source: "seed" },
  { at: t(42), direction: "in", category: "creator-fees", amount: "0.88", asset: "ETH", memo: "Pons creator tax — week 6", source: "seed" },
  { at: t(35), direction: "in", category: "creator-fees", amount: "1.21", asset: "ETH", memo: "Pons creator tax — week 7", source: "seed" },
  { at: t(28), direction: "in", category: "creator-fees", amount: "1.36", asset: "ETH", memo: "Pons creator tax — week 8", source: "seed" },
  { at: t(21), direction: "in", category: "creator-fees", amount: "1.18", asset: "ETH", memo: "Pons creator tax — week 9", source: "seed" },
  { at: t(14), direction: "in", category: "creator-fees", amount: "1.64", asset: "ETH", memo: "Pons creator tax — week 10", source: "seed" },
  { at: t(7), direction: "in", category: "creator-fees", amount: "1.83", asset: "ETH", memo: "Pons creator tax — week 11", source: "seed" },
  { at: t(1), direction: "in", category: "creator-fees", amount: "2.02", asset: "ETH", memo: "Pons creator tax — week 12", source: "seed" },
  // Infrastructure + ecosystem spending (out).
  { at: t(60), direction: "out", category: "compute", amount: "0.31", asset: "ETH", memo: "Hyperbolic inference — July", source: "seed" },
  { at: t(30), direction: "out", category: "compute", amount: "0.47", asset: "ETH", memo: "Hyperbolic inference — August", source: "seed" },
  { at: t(60), direction: "out", category: "data", amount: "0.12", asset: "ETH", memo: "MongoDB Atlas — July", source: "seed" },
  { at: t(30), direction: "out", category: "data", amount: "0.14", asset: "ETH", memo: "MongoDB Atlas — August", source: "seed" },
  { at: t(58), direction: "out", category: "rpc", amount: "0.09", asset: "ETH", memo: "RPC + archive nodes — July", source: "seed" },
  { at: t(28), direction: "out", category: "rpc", amount: "0.11", asset: "ETH", memo: "RPC + archive nodes — August", source: "seed" },
  { at: t(55), direction: "out", category: "hosting", amount: "0.05", asset: "ETH", memo: "Hosting + CDN — July", source: "seed" },
  { at: t(25), direction: "out", category: "hosting", amount: "0.05", asset: "ETH", memo: "Hosting + CDN — August", source: "seed" },
  { at: t(50), direction: "out", category: "indexing", amount: "0.07", asset: "ETH", memo: "Fee + execution indexers", source: "seed" },
  { at: t(44), direction: "out", category: "security", amount: "0.60", asset: "ETH", memo: "Contract review — OperatorBudget/FeeVault", source: "seed" },
  { at: t(26), direction: "out", category: "grants", amount: "0.50", asset: "ETH", memo: "Grant FIP-G2 — open-source memory tooling", source: "seed" },
  { at: t(13), direction: "out", category: "incentives", amount: "0.35", asset: "ETH", memo: "Aviary publisher incentives — cohort 1", source: "seed" },
  { at: t(6), direction: "out", category: "subsidized-executions", amount: "0.22", asset: "ETH", memo: "Free-tier finch executions", source: "seed" },
];
